### ISSUE TITLE
Make Sam an owner of the repo

### ISSUE THREAD

**Issue by hershaw** [Daltix/snowconn#9]
Since I've taken responsibility for maintaining the repo, I really should AT LEAST have enough permissions to do releases and optimally be an owner of it so I can do anything else that needs to be done.

**Comment by sesprit** [comment]
Just saw this now, you had been invited but I think you lost the email?

See:
![image](https://user-images.githubusercontent.com/26927695/68030113-a689c080-fcb0-11e9-8ec9-12e367d122a5.png)

**Comment by hershaw** [comment]
yup! found it and it's done!
